// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace SCM1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    internal class ApplicationDbContextModelSnapshotBase
    {
    }
}